### ISSUE TITLE
Giga year ucum representation

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [FHIR/Ucum-java#13]
I am using the following ucum essence file:http://unitsofmeasure.org/ucum-essence.xml
I cannot validate the unit 'Ga'.

```
try {
			UcumService ucumSvc = new UcumEssenceService("C:\\Users.....");
			System.out.print(ucumSvc.analyse("Ga"));
		} catch (UcumException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
```
		
Exception:
```
org.fhir.ucum.UcumException: Error processing unit 'Ga': The unit 'Ga' is unknown' at position 0
	at org.fhir.ucum.Lexer.error(Lexer.java:173)
	at org.fhir.ucum.ExpressionParser.parseSymbol(ExpressionParser.java:112)
	at org.fhir.ucum.ExpressionParser.parseComp(ExpressionParser.java:71)
	at org.fhir.ucum.ExpressionParser.parseTerm(ExpressionParser.java:47)
	at org.fhir.ucum.ExpressionParser.parse(ExpressionParser.java:28)
	at org.fhir.ucum.UcumEssenceService.analyse(UcumEssenceService.java:201)
```
What is the ucum representation of Gigayear?

**Comment by grahamegrieve** [comment]
There isn't one - year is a not a metric unit, so it can't have metric prefixes. That's how it's defined in UCUM
