### ISSUE TITLE
Exception getting canonical unit of dimensionless type (I think?)

### ISSUE THREAD

**Issue by labkey-matthewb** [FHIR/Ucum-java#23]
String c = ucum.getCanonicalUnits("dB");

results in : 

  org.fhir.ucum.UcumException: Error processing dB: Cannot invoke "org.fhir.ucum.Decimal.multiply(org.fhir.ucum.Decimal)" because "this.value" is null
            at org.fhir.ucum.UcumEssenceService.getCanonicalUnits(UcumEssenceService.java:215)
            at org.labkey.jsp.compiled.org.labkey.units.fhir.UcumTestCase_jsp.bugs(UcumTestCase_jsp.java:133)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:564)
            at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        java.lang.NullPointerException: Cannot invoke "org.fhir.ucum.Decimal.multiply(org.fhir.ucum.Decimal)" because "this.value" is null
            at org.fhir.ucum.Canonical.multiplyValue(Canonical.java:74)
            at org.fhir.ucum.Converter.normalise(Converter.java:128)
            at org.fhir.ucum.Converter.normalise(Converter.java:63)
            at org.fhir.ucum.Converter.convert(Converter.java:36)
            at org.fhir.ucum.UcumEssenceService.getCanonicalUnits(UcumEssenceService.java:213)

**Comment by grahamegrieve** [comment]
Works now, but added test to make sure
